# ?? ?? ?? (?? ??, ??? 8080)
server:
  port: 8080

# ??? ?? ??
spring:
  # ?????? ?? ??
  datasource:
    url: jdbc:mysql://localhost:3306/commerce_db
    username: root
    password: park010506@


  # JPA ? Hibernate(JPA ???) ?? ??
  jpa:
    hibernate:
      ddl-auto: update # 4. ?????? ?? ? ???? DB ???? ??? ???? ??/??
    properties:
      hibernate:
        show_sql: true # 5. JPA? ???? SQL ??? ??? ???
        format_sql: true # SQL? ??? ???
    open-in-view: false