server:
  port: 8080

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/commerce_db
    username: root
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

naver:
  api:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_API_CLIENT_SECRET}
